name: lex
description: Dart lexer for various programming languages.
version: 0.0.1
author: Thorsten Lorenz <thlorenz@gmx.de>
homepage: https://thlorenz.com

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  equatable: ^0.5.0

dev_dependencies:
  test: ^1.6.8

