name: lex
description: Dart lexer for various programming languages.
version: 0.0.1
# this pubspec field is deprecated, but credits go to this person, ofc
# author: Thorsten Lorenz <thlorenz@gmx.de>
homepage: https://thlorenz.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0
